pipeline{
    agent any
    stages{
        stage('Create Image'){
            steps{
                echo "Creating image"
                echo "${env.WORKSPACE}"
                dir("${env.WORKSPACE}"){
                    withCredentials([usernamePassword(credentialsId: 'DockerHubAccount', passwordVariable: 'DOCKERHUB_PWD', usernameVariable: 'DOCKHUB_USER')]) {
                        sh """
                            whoami
                            pwd
                            sudo docker build -f nginx_docker/Dockerfile -t harryhu/simple-nginx:0.0.1 nginx_docker
                        """
                    }
                }
            }
        }
        stage("Push Image"){
            withCredentials([usernamePassword(credentialsId: 'DockerHubAccount', passwordVariable: 'DOCKERHUB_PWD', usernameVariable: 'DOCKHUB_USER')]) {
                sh('echo $DOCKERHUB_PWD | sudo docker login -u=${DOCKHUB_USER} --password-stdin')
                sh('sudo docker push harryhu/simple-nginx:0.0.1')
            }
        }
        Stage("Cleanup"){
            sh('sudo docker rmi harryhu/simple-nginx:0.0.1')
        }
    }
}