script {
    tag = "1.0.${env.BUILD_NUMBER}"
}
pipeline{
    agent any
    stages{
        stage('Create Image'){
            steps{
                echo "Creating image"
                echo "${env.WORKSPACE}"
                dir("${env.WORKSPACE}"){
                    sh """
                        whoami
                        pwd
                        sudo docker build -f docker/Dockerfile -t harryhu/simple-nginx:${tag} docker
                    """
                }
            }
        }
        stage("Push Image"){
            steps{
                withCredentials([usernamePassword(credentialsId: 'DockerHubAccount', passwordVariable: 'DOCKERHUB_PWD', usernameVariable: 'DOCKHUB_USER')]) {
                    sh('echo $DOCKERHUB_PWD | sudo docker login -u=${DOCKHUB_USER} --password-stdin')
                    sh("sudo docker push harryhu/simple-nginx:${tag}")
                }
            }
        }
        stage("Cleanup"){
            steps{
                sh("sudo docker rmi harryhu/simple-nginx:${tag}")
            }
        }
        stage("Deploy"){
            steps{
                sh """
                    kubectl set image deployment/nginx -n nginx nginx-container=harryhu/simple-nginx:${tag}
                """
            }
        }
    }
}