# Yaml file example with anchor use

#namespace
apiVersion: v1
kind: Namespace
metadata:
  name: &mynamespace nginx
  labels:
    name: "nginx"

---
#deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: harryhu/simple-nginx:0.0.1
        ports:
        - containerPort: 80
---
#service
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: &port 80
      targetPort: *port
      nodePort: 30201

