FROM jenkins/jenkins:lts-jdk11
# The will force jenkins to run as root. Thus reduce some permission issue for Docker in Docker
USER root

RUN apt-get update 
RUN apt-get install -y sudo
RUN apt-get install make

#install docker
RUN apt-get install -y docker.io

#install kubectl
RUN curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
RUN touch /etc/apt/sources.list.d/kubernetes.list 
Run echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
RUN apt-get update
RUN apt-get install -y kubectl

#configure access to Minikube
ADD minikube/config /root/.kube/config
ADD minikube/ca.crt /root/.minikube/ca.crt
ADD minikube/client.crt /root/.minikube/profiles/minikube/client.crt
ADD minikube/client.key /root/.minikube/profiles/minikube/client.key
RUN kubectl version